### ISSUE TITLE
.NET 5.0 has gone EOL

### ISSUE THREAD

**Issue by mpkorstanje** [gasparnagy/berp#17]
```
dotnet tool update Berp --version 1.3.0 --tool-path .
You can invoke the tool using the following command: berp
Tool 'berp' (version '1.3.0') was successfully installed.
mpkorstanje@nyx $ ./berp 
You must install or update .NET to run this application.

App: /home/mpkorstanje/Projects/cucumber/gherkin/berp
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: /usr/lib/dotnet/dotnet6-6.0.110

The following frameworks were found:
  6.0.10 at [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=ubuntu.22.04-x64
```

And then looking to install .NET 5, we see:

> This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as [6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime). See our [support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) for more details.

Can you release a version for .NET 6?

**Comment by chybz** [comment]
@mpkorstanje 
Tested locally here, if you change `net5.0` to `net6.0` in `*.csproj` files, and:
```shell
$ dotnet build -c Release
```
in `src` sub-directory, it produces a usable Berp tool.

**Comment by mpkorstanje** [comment]
Cheers! I was hoping @gasparnagy could change that and push a new release to NuGet.

While I could build it myself and use that artifact, we are using this in [cucumber/gherkin](https://github.com/cucumber/gherkin)(to which Gaspar is also a contributor), so being able to use `dotnet tool update Berp` greatly simplifies things.

**Comment by gasparnagy** [comment]
Thx! The new version (v1.4.0) is on NuGet now. It supports both .NET 6 and .NET 7.
