### ISSUE TITLE
--version should exit with status 0

### ISSUE THREAD

**Issue by mpkorstanje** [gasparnagy/berp#18]
```
cukebot@f2d99e5daf4b:/app/javascript$ berp --version
Berp 1.3.0
cukebot@f2d99e5daf4b:/app/javascript$ echo $?
2
```

Otherwise it's hard to check if Berp is installed with the right version in CI (non-zero exit, will often cause any build job to terminate) .

**Comment by gasparnagy** [comment]
fixed in v1.4.0
